-- Materialization for a model
--{{config(Materialization='table')}}



WITH DAILY_WEATHER AS (

SELECT 
DATE(TIME) AS DAILY_WEATHER_DATE,
WEATHER,
TEMP, 
PRESSURE,
HUMIDITY,
CLOUDS

FROM {{source("demo","WEATHER")}}


),
DAILY_WEATHER_AGG AS (

SELECT 
DAILY_WEATHER_DATE,
WEATHER,
ROUND(AVG(TEMP),2) as avg_temp, 
ROUND(AVG(PRESSURE),2) as avg_pressure,
ROUND(AVG(HUMIDITY),2) as avg_humidity,
ROUND(AVG(CLOUDS),2) as avg_clouds
--COUNT(WEATHER) AS COUNT_W,
--ROW_NUMBER() OVER (PARTITION BY DAILY_WEATHER_DATE ORDER BY COUNT_W DESC, WEATHER ASC) AS row_number
FROM DAILY_WEATHER
GROUP BY DAILY_WEATHER_DATE,WEATHER
QUALIFY ROW_NUMBER() OVER (PARTITION BY DAILY_WEATHER_DATE ORDER BY COUNT(WEATHER) DESC, WEATHER ASC) = 1
ORDER BY DAILY_WEATHER_DATE
)

SELECT *
FROM DAILY_WEATHER_AGG