with CTE as (

select
TO_TIMESTAMP(STARTED_AT), STARTED_AT, 
DATE(TO_TIMESTAMP(STARTED_AT)) AS DATE_START,
HOUR(TO_TIMESTAMP(STARTED_AT)) AS HOURS_DATE,
MINUTE(TO_TIMESTAMP(STARTED_AT)) AS MINUTE_DATE,
SECOND(TO_TIMESTAMP(STARTED_AT)) AS SECONDE_DATE,
MONTH(TO_TIMESTAMP(STARTED_AT)) AS MONTH_DATE,
MONTHNAME(TO_TIMESTAMP(STARTED_AT)) AS MONTHNAME_DATE,
DAY(TO_TIMESTAMP(STARTED_AT)) AS DAY_DATE,
DAYNAME(TO_TIMESTAMP(STARTED_AT)) AS DAYNAME_DATE,
DAYOFWEEK(TO_TIMESTAMP(STARTED_AT)) AS DAY_OF_WEEK,
CASE
WHEN DAYNAME(TO_TIMESTAMP(STARTED_AT)) = ('Sat') then 'Samedi'
WHEN DAYNAME(TO_TIMESTAMP(STARTED_AT)) = ('Sun') then 'Dimanche'
WHEN DAYNAME(TO_TIMESTAMP(STARTED_AT)) = ('Mon') then 'Lundi'
WHEN DAYNAME(TO_TIMESTAMP(STARTED_AT)) = ('Tue') then 'Mardi'
WHEN DAYNAME(TO_TIMESTAMP(STARTED_AT)) = ('Wed') then 'Mercredi'
WHEN DAYNAME(TO_TIMESTAMP(STARTED_AT)) = ('Thu') then 'Jeudi'
Else 'Vendredi' END AS jours_Semaine_FR,

Case 
WHEN DAYNAME(TO_TIMESTAMP(STARTED_AT)) in ('Sat','Sun') then 'Fin de semaine'
else 'Jours de semaine'
end as Type_Date,

{{day_type('STARTED_AT')}} AS DateType,

QUARTER(TO_TIMESTAMP(STARTED_AT)) AS QUARTER_Y,

CASE 
WHEN QUARTER(TO_TIMESTAMP(STARTED_AT)) = 1 THEN 'Q1'
WHEN QUARTER(TO_TIMESTAMP(STARTED_AT)) = 2 THEN 'Q2'
WHEN QUARTER(TO_TIMESTAMP(STARTED_AT)) = 3 THEN 'Q3'
WHEN QUARTER(TO_TIMESTAMP(STARTED_AT)) = 4 THEN 'Q4'
END AS Quarter_Q,

CASE
WHEN ((MONTH(TO_TIMESTAMP(STARTED_AT)) = 12 AND  DAY(TO_TIMESTAMP(STARTED_AT))>=  21) 
OR (MONTH(TO_TIMESTAMP(STARTED_AT)) IN (1,2)) 
OR (MONTH(TO_TIMESTAMP(STARTED_AT)) = 3 AND  DAY(TO_TIMESTAMP(STARTED_AT)) <=  20))  THEN 'Winter'

WHEN ((MONTH(TO_TIMESTAMP(STARTED_AT)) = 3 AND  DAY(TO_TIMESTAMP(STARTED_AT))>=  21) 
OR (MONTH(TO_TIMESTAMP(STARTED_AT)) IN (4,5)) 
OR (MONTH(TO_TIMESTAMP(STARTED_AT)) = 6 AND  DAY(TO_TIMESTAMP(STARTED_AT)) <=  20))  THEN 'Spring'

WHEN ((MONTH(TO_TIMESTAMP(STARTED_AT)) = 6 AND  DAY(TO_TIMESTAMP(STARTED_AT))>=  21) 
OR (MONTH(TO_TIMESTAMP(STARTED_AT)) IN (7,8)) 
OR (MONTH(TO_TIMESTAMP(STARTED_AT)) = 9 AND  DAY(TO_TIMESTAMP(STARTED_AT)) <=  20))  THEN 'Summer'

ELSE 'Fall/Automn' END AS Season,

{#{{funDate('STARTED_AT')}} AS P_F #}

{{ funSeason("STARTED_AT") }} AS Season2




from 
{{ source('demo', 'BIKE') }}

WHERE   TRY_TO_TIMESTAMP(STARTED_AT) IS NOT NULL
--AND DAYOFWEEK(TRY_TO_TIMESTAMP(STARTED_AT)) IN (0,6)

)

SELECT 
*
FROM CTE


