WITH BIKE AS (

SELECT 
RIDE_ID,
DATE(TO_TIMESTAMP(STARTED_AT)) AS TRIP_DATE,
START_STATION_ID ,
END_STATION_ID,
MEMBER_CSUAL AS MEMBER_CASUAL,
DATEDIFF(minute, TO_TIMESTAMP(STARTED_AT), TO_TIMESTAMP(ENDED_AT)) AS TRIP_DURATION_MINUTES
FROM {{ ref('stg_bike') }}
where RIDE_ID != '"bikeid"' or RIDE_ID != 'bikeid' or STARTED_AT !=  'starttime' or ENDED_AT !=  'stoptime'
)

SELECT
*
FROM BIKE