WITH BIKE AS (

SELECT 
RIDE_ID,
RIDEABLE_TYPE,
DATE(TO_TIMESTAMP(STARTED_AT)) AS TRIP_DATE,
START_STATION_ID ,
END_STATION_ID,
MEMBER_CSUAL AS MEMBER_CASUAL,
--ENDED_AT,
--STARTED_AT,
DATEDIFF(minute, TO_TIMESTAMP(STARTED_AT), TO_TIMESTAMP(ENDED_AT)) AS TRIP_DURATION_MINUTES
FROM {{ source('demo', 'BIKE') }}
WHERE RIDE_ID <> 'ride_id'
--ORDER BY TRIP_DURATION_MINUTES DESC
--LIMIT 500
)

SELECT
*
FROM BIKE